export const mockExams = [
  {
    id: '1',
    patientName: 'John Doe',
    patientId: 'PT001',
    modality: 'CT',
    studyDate: '2024-03-20',
    studyTime: '14:30',
    description: 'Chest CT With Contrast',
    status: 'completed',
    imageCount: 247,
    referringPhysician: 'Dr. Sarah Wilson',
  },
  {
    id: '2',
    patientName: 'Jane Smith',
    patientId: 'PT002',
    modality: 'MRI',
    studyDate: '2024-03-20',
    studyTime: '09:15',
    description: 'Brain MRI Without Contrast',
    status: 'in-progress',
    imageCount: 183,
    referringPhysician: 'Dr. Michael Chen',
  },
  {
    id: '3',
    patientName: 'Robert Johnson',
    patientId: 'PT003',
    modality: 'XR',
    studyDate: '2024-03-19',
    studyTime: '16:45',
    description: 'Chest X-Ray PA and Lateral',
    status: 'completed',
    imageCount: 2,
    referringPhysician: 'Dr. Emily Brown',
  },
] as const;